import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import AppBar from "@/components/AppBar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "InfiniteHealings.in | Home Page",
  description: "Generated by create next app",
  keywords : ""
};
import { cn } from "@/lib/utils"

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        {children}
        </body>
    </html>
  );
}
